ifndef TA_DEV_KIT_DIR
$(error TA_DEV_KIT_DIR is not set)
endif

BINARY := 12345679-9abc-4def-8123-456789abcdef

# Verbose TA logs
CFLAGS += -DTA_LOG_LEVEL=4

include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk