ifndef TA_DEV_KIT_DIR
$(error TA_DEV_KIT_DIR is not set)
endif

# Must match the UUID you use in the host client:
BINARY := 7f3b8d40-6c6a-4f2b-914c-39389d1244a1

# Do NOT list sources here. sub.mk will.
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk